// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUVimdh6kCVNInPL3VrnWx6T3zf2tWw0M',
    appId: '1:980098642909:web:8e83f584f0321f034abc34',
    messagingSenderId: '980098642909',
    projectId: 'sprout-7f63c',
    authDomain: 'sprout-7f63c.firebaseapp.com',
    storageBucket: 'sprout-7f63c.appspot.com',
    measurementId: 'G-BGMF7K1RCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsmuNgIxFVmiBkr8y0o3hqLu0ip4lAXnk',
    appId: '1:980098642909:android:17f3a049bf39d3934abc34',
    messagingSenderId: '980098642909',
    projectId: 'sprout-7f63c',
    storageBucket: 'sprout-7f63c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx10JCXMHkIAW11t9uiH-Tejt413H3-yM',
    appId: '1:980098642909:ios:8b0b795ea5e98f0f4abc34',
    messagingSenderId: '980098642909',
    projectId: 'sprout-7f63c',
    storageBucket: 'sprout-7f63c.appspot.com',
    iosClientId: '980098642909-7fk2rt6cop3ocainlltl6rg5o2jh5vae.apps.googleusercontent.com',
    iosBundleId: 'me.lucianolim.sprout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx10JCXMHkIAW11t9uiH-Tejt413H3-yM',
    appId: '1:980098642909:ios:8b0b795ea5e98f0f4abc34',
    messagingSenderId: '980098642909',
    projectId: 'sprout-7f63c',
    storageBucket: 'sprout-7f63c.appspot.com',
    iosClientId: '980098642909-7fk2rt6cop3ocainlltl6rg5o2jh5vae.apps.googleusercontent.com',
    iosBundleId: 'me.lucianolim.sprout',
  );
}
